const languageData = {
  "CN": { name: "中国", flag: "🇨🇳", language: "中文 (普通话)", family: "Sino-Tibetan", speakers: "10亿+", fact: "中文是世界上使用人数最多的母语。", neighbors: ["JP", "KR", "MN", "KZ", "NP", "IN", "MM", "LA", "VN"] },
  "US": { name: "美国", flag: "🇺🇸", language: "英语", family: "Indo-European", speakers: "3亿+", fact: "美国没有官方语言，但英语是事实上的官方语言。", neighbors: ["CA", "MX"] },
  "GB": { name: "英国", flag: "🇬🇧", language: "英语", family: "Indo-European", speakers: "6700万", fact: "英语起源于英格兰，如今是全球通用语言。", neighbors: ["IE"] },
  "FR": { name: "法国", flag: "🇫🇷", language: "法语", family: "Indo-European", speakers: "7600万", fact: "法语是联合国六大工作语言之一。", neighbors: ["BE", "DE", "CH", "IT", "ES"] },
  "DE": { name: "德国", flag: "🇩🇪", language: "德语", family: "Indo-European", speakers: "1亿+", fact: "德语是欧盟使用人数最多的母语。", neighbors: ["DK", "PL", "CZ", "AT", "CH", "BE", "NL", "FR"] },
  "JP": { name: "日本", flag: "🇯🇵", language: "日语", family: "Japonic", speakers: "1.26亿", fact: "日语拥有完整的敬语系统。", neighbors: ["CN", "KR"] },
  "KR": { name: "韩国", flag: "🇰🇷", language: "韩语", family: "Other", speakers: "7700万", fact: "韩语字母表谚文是1443年由世宗大王创制。", neighbors: ["KP", "CN", "JP"] },
  "RU": { name: "俄罗斯", flag: "🇷🇺", language: "俄语", family: "Indo-European", speakers: "1.44亿", fact: "俄语是联合国六种工作语言之一。", neighbors: ["NO", "FI", "EE", "LV", "LT", "PL", "BY", "UA", "GE", "KZ", "CN", "KP"] },
  "IN": { name: "印度", flag: "🇮🇳", language: "印地语", family: "Indo-European", speakers: "6亿+", fact: "印度有22种官方语言。", neighbors: ["CN", "NP", "BT", "MM", "BD", "PK", "AF"] },
  "BR": { name: "巴西", flag: "🇧🇷", language: "葡萄牙语", family: "Indo-European", speakers: "2.1亿", fact: "巴西是世界上最大的葡萄牙语使用者国家。", neighbors: ["AR", "BO", "CO", "PY", "PE", "UY"] },
  "AR": { name: "阿根廷", flag: "🇦🇷", language: "西班牙语", family: "Indo-European", speakers: "4500万", fact: "阿根廷西班牙语有独特的口音。", neighbors: ["BO", "BR", "CL", "PY", "UY"] },
  "MX": { name: "墨西哥", flag: "🇲🇽", language: "西班牙语", family: "Indo-European", speakers: "1.26亿", fact: "墨西哥是西班牙语使用人数最多的国家。", neighbors: ["GT", "US"] },
  "ES": { name: "西班牙", flag: "🇪🇸", language: "西班牙语", family: "Indo-European", speakers: "4300万", fact: "西班牙语是世界上第二大母语。", neighbors: ["PT", "FR"] },
  "IT": { name: "意大利", flag: "🇮🇹", language: "意大利语", family: "Indo-European", speakers: "6800万", fact: "意大利语被认为是世界上最美妙的语言之一。", neighbors: ["FR", "CH", "AT", "SI", "VA"] },
  "AU": { name: "澳大利亚", flag: "🇦🇺", language: "英语", family: "Indo-European", speakers: "2500万", fact: "澳大利亚有250多种土著语言。", neighbors: [] },
  "CA": { name: "加拿大", flag: "🇨🇦", language: "英语/法语", family: "Indo-European", speakers: "3800万", fact: "加拿大是双语国家。", neighbors: ["US"] },
  "ZA": { name: "南非", flag: "🇿🇦", language: "祖鲁语/科萨语/英语", family: "Niger-Congo", speakers: "3500万", fact: "南非有11种官方语言。", neighbors: ["ZW", "MZ", "BW", "NA"] },
  "EG": { name: "埃及", flag: "🇪🇬", language: "阿拉伯语", family: "Afro-Asiatic", speakers: "1.02亿", fact: "古埃及文字是人类最古老的书写系统之一。", neighbors: ["LY", "SD", "IL"] },
  "SA": { name: "沙特阿拉伯", flag: "🇸🇦", language: "阿拉伯语", family: "Afro-Asiatic", speakers: "3500万", fact: "阿拉伯语从右向左书写。", neighbors: ["IQ", "JO", "KW", "OM", "QA", "YE", "AE"] },
  "TR": { name: "土耳其", flag: "🇹🇷", language: "土耳其语", family: "Turkic", speakers: "8500万", fact: "土耳其语1928年改为拉丁字母。", neighbors: ["GR", "BG", "GE", "AM", "IR", "IQ", "SY"] },
  "IR": { name: "伊朗", flag: "🇮🇷", language: "波斯语", family: "Indo-European", speakers: "8700万", fact: "波斯语拥有3000多年的悠久历史。", neighbors: ["IQ", "TM", "AF", "PK", "TR", "AZ"] },
  "ID": { name: "印度尼西亚", flag: "🇮🇩", language: "印尼语", family: "Austronesian", speakers: "2.7亿", fact: "印尼拥有700多种语言。", neighbors: ["MY", "PG"] },
  "TH": { name: "泰国", flag: "🇹🇭", language: "泰语", family: "Other", speakers: "7000万", fact: "泰语有自己的文字系统。", neighbors: ["MM", "LA", "KH", "MY"] },
  "VN": { name: "越南", flag: "🇻🇳", language: "越南语", family: "Austronesian", speakers: "9700万", fact: "越南语使用拉丁字母的国语字。", neighbors: ["CN", "LA", "KH"] },
  "PH": { name: "菲律宾", flag: "🇵🇭", language: "菲律宾语/英语", family: "Austronesian", speakers: "1.1亿", fact: "菲律宾有170多种语言。", neighbors: [] },
  "MY": { name: "马来西亚", flag: "🇲🇾", language: "马来语", family: "Austronesian", speakers: "3300万", fact: "马来语使用拉丁字母书写。", neighbors: ["TH", "BN"] },
  "SG": { name: "新加坡", flag: "🇸🇬", language: "英语/华语/马来语/泰米尔语", family: "Austronesian", speakers: "590万", fact: "新加坡有四种官方语言。", neighbors: [] },
  "NL": { name: "荷兰", flag: "🇳🇱", language: "荷兰语", family: "Indo-European", speakers: "2500万", fact: "荷兰语在比利时和苏里南也是官方语言。", neighbors: ["BE", "DE"] },
  "BE": { name: "比利时", flag: "🇧🇪", language: "荷兰语/法语/德语", family: "Indo-European", speakers: "1150万", fact: "比利时使用三种官方语言。", neighbors: ["FR", "DE", "NL", "LU"] },
  "SE": { name: "瑞典", flag: "🇸🇪", language: "瑞典语", family: "Indo-European", speakers: "1000万", fact: "瑞典语与挪威语和丹麦语相近。", neighbors: ["NO", "FI"] },
  "NO": { name: "挪威", flag: "🇳🇴", language: "挪威语", family: "Indo-European", speakers: "530万", fact: "挪威语有两种书面标准。", neighbors: ["SE", "FI", "RU"] },
  "DK": { name: "丹麦", flag: "🇩🇰", language: "丹麦语", family: "Indo-European", speakers: "590万", fact: "丹麦语以其难发的语音闻名。", neighbors: ["DE"] },
  "FI": { name: "芬兰", flag: "🇫🇮", language: "芬兰语", family: "Other", speakers: "540万", fact: "芬兰语属于乌拉尔语系。", neighbors: ["SE", "NO", "RU"] },
  "PL": { name: "波兰", flag: "🇵🇱", language: "波兰语", family: "Indo-European", speakers: "3800万", fact: "波兰语有独特的字母。", neighbors: ["DE", "CZ", "SK", "UA", "BY", "LT", "RU"] },
  "UA": { name: "乌克兰", flag: "🇺🇦", language: "乌克兰语", family: "Indo-European", speakers: "4100万", fact: "乌克兰语使用西里尔字母。", neighbors: ["RU", "BY", "PL", "SK", "HU", "RO"] },
  "GR": { name: "希腊", flag: "🇬🇷", language: "希腊语", family: "Indo-European", speakers: "1100万", fact: "希腊语是西方最古老的语言之一。", neighbors: ["AL", "MK", "BG", "TR"] },
  "PT": { name: "葡萄牙", flag: "🇵🇹", language: "葡萄牙语", family: "Indo-European", speakers: "2500万", fact: "葡萄牙语是全球第七大语言。", neighbors: ["ES"] },
  "CH": { name: "瑞士", flag: "🇨🇭", language: "德语/法语/意大利语/罗姆语", family: "Indo-European", speakers: "870万", fact: "瑞士有四种官方语言。", neighbors: ["DE", "FR", "IT", "AT"] },
  "AT": { name: "奥地利", flag: "🇦🇹", language: "德语", family: "Indo-European", speakers: "900万", fact: "奥地利德语与德国德语略有不同。", neighbors: ["DE", "CZ", "SK", "HU", "SI", "IT", "CH"] },
  "CO": { name: "哥伦比亚", flag: "🇨🇴", language: "西班牙语", family: "Indo-European", speakers: "5100万", fact: "哥伦比亚的西班牙语以其清晰的发音著称。", neighbors: ["VE", "BR", "PE", "EC", "PA"] },
  "PE": { name: "秘鲁", flag: "🇵🇪", language: "西班牙语/克丘亚语", family: "Indo-European", speakers: "3400万", fact: "克丘亚语是前哥伦布时期最重要的土著语言。", neighbors: ["EC", "BR", "BO", "CL"] },
  "CL": { name: "智利", flag: "🇨🇱", language: "西班牙语", family: "Indo-European", speakers: "1900万", fact: "智利是拉丁美洲最稳定的国家之一。", neighbors: ["AR", "BO", "PE"] },
  "NG": { name: "尼日利亚", flag: "🇳🇬", language: "英语", family: "Indo-European", speakers: "2.06亿", fact: "尼日利亚是非洲人口最多的国家。", neighbors: ["BJ", "TD", "CM"] },
  "KE": { name: "肯尼亚", flag: "🇰🇪", language: "斯瓦希里语/英语", family: "Niger-Congo", speakers: "5400万", fact: "斯瓦希里语是非洲使用最广泛的语言之一。", neighbors: ["TZ", "UG", "SO", "ET"] },
  "MA": { name: "摩洛哥", flag: "🇲🇦", language: "阿拉伯语/柏柏尔语", family: "Afro-Asiatic", speakers: "3700万", fact: "摩洛哥使用阿拉伯语和柏柏尔语两种官方语言。", neighbors: ["DZ"] },
  "NZ": { name: "新西兰", flag: "🇳🇿", language: "英语/毛利语", family: "Indo-European", speakers: "510万", fact: "毛利语是新西兰的官方语言之一。", neighbors: [] },
  "AE": { name: "阿联酋", flag: "🇦🇪", language: "阿拉伯语", family: "Afro-Asiatic", speakers: "990万", fact: "阿联酋的官方语言是阿拉伯语。", neighbors: ["SA", "OM", "QA"] },
  "RO": { name: "罗马尼亚", flag: "🇷🇴", language: "罗马尼亚语", family: "Indo-European", speakers: "2500万", fact: "罗马尼亚语是唯一存活的罗曼语东部分支。", neighbors: ["HU", "RS", "BG", "UA"] },
  "CZ": { name: "捷克", flag: "🇨🇿", language: "捷克语", family: "Indo-European", speakers: "1070万", fact: "捷克语以其复杂的词形变化著称。", neighbors: ["DE", "PL", "SK", "AT"] },
  "HU": { name: "匈牙利", flag: "🇭🇺", language: "匈牙利语", family: "Other", speakers: "1300万", fact: "匈牙利语属于乌拉尔语系，与芬兰语有远亲关系。", neighbors: ["SK", "UA", "RO", "RS", "HR", "AT", "SI"] },
  "IE": { name: "爱尔兰", flag: "🇮🇪", language: "英语/爱尔兰语", family: "Indo-European", speakers: "500万", fact: "爱尔兰语是欧盟官方语言中最早的古典语言。", neighbors: ["GB"] },
  "HK": { name: "香港", flag: "🇭🇰", language: "中文/英语", family: "Sino-Tibetan", speakers: "750万", fact: "香港实行两文三语政策。", neighbors: ["CN"] },
  "TW": { name: "台湾", flag: "🇹🇼", language: "中文 (国语)", family: "Sino-Tibetan", speakers: "2350万", fact: "台湾使用繁体中文。", neighbors: ["CN", "JP"] },
  "NP": { name: "尼泊尔", flag: "🇳🇵", language: "尼泊尔语", family: "Indo-European", speakers: "3000万", fact: "尼泊尔语使用天城文书写。", neighbors: ["CN", "IN"] },
  "MM": { name: "缅甸", flag: "🇲🇲", language: "缅甸语", family: "Other", speakers: "6800万", fact: "缅甸语使用独特的圆形字母。", neighbors: ["CN", "TH", "BD", "IN"] },
  "BD": { name: "孟加拉国", flag: "🇧🇩", language: "孟加拉语", family: "Indo-European", speakers: "1.7亿", fact: "孟加拉语是印欧语系中最接近梵语的语言之一。", neighbors: ["IN", "MM"] },
  "PK": { name: "巴基斯坦", flag: "🇵🇰", language: "乌尔都语", family: "Indo-European", speakers: "2.2亿", fact: "乌尔都语使用波斯-阿拉伯字母。", neighbors: ["IN", "AF", "IR"] },
  "AF": { name: "阿富汗", flag: "🇦🇫", language: "普什图语/达里语", family: "Indo-European", speakers: "4000万", fact: "阿富汗有多种官方语言。", neighbors: ["PK", "TM", "UZ", "TJ", "CN"] },
  "IQ": { name: "伊拉克", flag: "🇮🇶", language: "阿拉伯语", family: "Afro-Asiatic", speakers: "4100万", fact: "伊拉克的阿拉伯语有独特的方言。", neighbors: ["SA", "IR", "TR", "SY", "JO"] },
  "SY": { name: "叙利亚", flag: "🇸🇾", language: "阿拉伯语", family: "Afro-Asiatic", speakers: "2100万", fact: "叙利亚的阿拉伯语有多种方言。", neighbors: ["TR", "IL", "JO", "IQ"] },
  "IL": { name: "以色列", flag: "🇮🇱", language: "希伯来语", family: "Afro-Asiatic", speakers: "950万", fact: "希伯来语是古老的复兴语言。", neighbors: ["EG", "JO", "LB", "SY"] },
  "JO": { name: "约旦", flag: "🇯🇴", language: "阿拉伯语", family: "Afro-Asiatic", speakers: "1100万", fact: "约旦的阿拉伯语是标准阿拉伯语的一种。", neighbors: ["SA", "IQ", "SY", "IL"] },
  "KW": { name: "科威特", flag: "🇰🇼", language: "阿拉伯语", family: "Afro-Asiatic", speakers: "430万", fact: "科威特的阿拉伯语有独特的方言。", neighbors: ["SA", "IQ"] },
  "QA": { name: "卡塔尔", flag: "🇶🇦", language: "阿拉伯语", family: "Afro-Asiatic", speakers: "290万", fact: "卡塔尔以天然气和石油财富闻名。", neighbors: ["SA", "AE"] },
  "OM": { name: "阿曼", flag: "🇴🇲", language: "阿拉伯语", family: "Afro-Asiatic", speakers: "520万", fact: "阿曼的阿拉伯语有独特的方言。", neighbors: ["SA", "YE", "AE"] },
  "KH": { name: "柬埔寨", flag: "🇰🇭", language: "高棉语", family: "Austronesian", speakers: "1700万", fact: "高棉语是东南亚最古老的语言之一。", neighbors: ["TH", "LA", "VN"] },
  "LA": { name: "老挝", flag: "🇱🇦", language: "老挝语", family: "Other", speakers: "750万", fact: "老挝语使用独特的字母系统。", neighbors: ["CN", "MM", "TH", "KH", "VN"] },
  "AM": { name: "亚美尼亚", flag: "🇦🇲", language: "亚美尼亚语", family: "Indo-European", speakers: "300万", fact: "亚美尼亚语有自己独特的字母。", neighbors: ["TR", "GE", "AZ", "IR"] },
  "GE": { name: "格鲁吉亚", flag: "🇬🇪", language: "格鲁吉亚语", family: "Other", speakers: "370万", fact: "格鲁吉亚语有自己独特的字母系统。", neighbors: ["RU", "TR", "AM", "AZ"] },
  "AZ": { name: "阿塞拜疆", flag: "🇦🇿", language: "阿塞拜疆语", family: "Turkic", speakers: "1030万", fact: "阿塞拜疆语使用拉丁字母。", neighbors: ["RU", "GE", "AM", "IR", "TR"] },
  "KZ": { name: "哈萨克斯坦", flag: "🇰🇿", language: "哈萨克语/俄语", family: "Turkic", speakers: "1950万", fact: "哈萨克斯坦是中亚最大的国家。", neighbors: ["RU", "CN", "KG", "UZ"] },
  "UZ": { name: "乌兹别克斯坦", flag: "🇺🇿", language: "乌兹别克语", family: "Turkic", speakers: "3400万", fact: "乌兹别克语使用拉丁字母。", neighbors: ["KZ", "KG", "TJ", "AF"] },
  "KG": { name: "吉尔吉斯斯坦", flag: "🇰🇬", language: "吉尔吉斯语", family: "Turkic", speakers: "670万", fact: "吉尔吉斯语使用西里尔字母。", neighbors: ["KZ", "CN", "TJ", "UZ"] },
  "TJ": { name: "塔吉克斯坦", flag: "🇹🇯", language: "塔吉克语", family: "Indo-European", speakers: "1000万", fact: "塔吉克语使用波斯字母。", neighbors: ["KG", "UZ", "AF", "CN"] },
  "TM": { name: "土库曼斯坦", flag: "🇹🇲", language: "土库曼语", family: "Turkic", speakers: "610万", fact: "土库曼语使用拉丁字母。", neighbors: ["KZ", "UZ", "AF", "IR"] },
  "MN": { name: "蒙古", flag: "🇲🇳", language: "蒙古语", family: "Other", speakers: "340万", fact: "蒙古语使用传统的竖写字母。", neighbors: ["RU", "CN"] },
  "KP": { name: "朝鲜", flag: "🇰🇵", language: "朝鲜语", family: "Other", speakers: "2600万", fact: "朝鲜语在南北韩有微小差异。", neighbors: ["CN", "KR", "RU"] },
  "HR": { name: "克罗地亚", flag: "🇭🇷", language: "克罗地亚语", family: "Indo-European", speakers: "400万", fact: "克罗地亚语使用拉丁字母。", neighbors: ["SI", "HU", "RS", "BA"] },
  "RS": { name: "塞尔维亚", flag: "🇷🇸", language: "塞尔维亚语", family: "Indo-European", speakers: "700万", fact: "塞尔维亚语使用西里尔字母。", neighbors: ["HU", "RO", "BG", "MK", "BA", "HR"] },
  "BA": { name: "波斯尼亚和黑塞哥维那", flag: "🇧🇦", language: "波斯尼亚语", family: "Indo-European", speakers: "330万", fact: "波斯尼亚语是波斯尼亚的官方语言。", neighbors: ["HR", "RS", "ME"] },
  "ME": { name: "黑山", flag: "🇲🇪", language: "黑山语", family: "Indo-European", speakers: "62万", fact: "黑山语是黑山的官方语言。", neighbors: ["RS", "HR", "AL"] },
  "SI": { name: "斯洛文尼亚", flag: "🇸🇮", language: "斯洛文尼亚语", family: "Indo-European", speakers: "210万", fact: "斯洛文尼亚语是斯洛文尼亚的官方语言。", neighbors: ["IT", "AT", "HU", "HR"] },
  "SK": { name: "斯洛伐克", flag: "🇸🇰", language: "斯洛伐克语", family: "Indo-European", speakers: "540万", fact: "斯洛伐克语与捷克语很相似。", neighbors: ["CZ", "PL", "UA", "HU", "AT"] },
  "BG": { name: "保加利亚", flag: "🇧🇬", language: "保加利亚语", family: "Indo-European", speakers: "700万", fact: "保加利亚语使用西里尔字母。", neighbors: ["RO", "RS", "MK", "GR", "TR"] },
  "MK": { name: "北马其顿", flag: "🇲🇰", language: "马其顿语", family: "Indo-European", speakers: "210万", fact: "马其顿语是马其顿的官方语言。", neighbors: ["RS", "BG", "GR", "AL"] },
  "AL": { name: "阿尔巴尼亚", flag: "🇦🇱", language: "阿尔巴尼亚语", family: "Indo-European", speakers: "290万", fact: "阿尔巴尼亚语有独特的字母。", neighbors: ["ME", "RS", "MK", "GR"] },
  "LT": { name: "立陶宛", flag: "🇱🇹", language: "立陶宛语", family: "Indo-European", speakers: "280万", fact: "立陶宛语是波罗的语族中最古老的语言。", neighbors: ["RU", "BY", "LV", "PL"] },
  "LV": { name: "拉脱维亚", flag: "🇱🇻", language: "拉脱维亚语", family: "Indo-European", speakers: "190万", fact: "拉脱维亚语属于波罗的语族。", neighbors: ["RU", "EE", "LT", "BY"] },
  "EE": { name: "爱沙尼亚", flag: "🇪🇪", language: "爱沙尼亚语", family: "Other", speakers: "110万", fact: "爱沙尼亚语属于乌拉尔语系。", neighbors: ["RU", "LV"] },
  "BY": { name: "白俄罗斯", flag: "🇧🇾", language: "白俄罗斯语/俄语", family: "Indo-European", speakers: "950万", fact: "白俄罗斯语使用西里尔字母。", neighbors: ["RU", "UA", "PL", "LT", "LV"] },
  "MD": { name: "摩尔多瓦", flag: "🇲🇩", language: "罗马尼亚语", family: "Indo-European", speakers: "260万", fact: "摩尔多瓦语与罗马尼亚语几乎相同。", neighbors: ["RO", "UA"] },
  "IS": { name: "冰岛", flag: "🇮🇸", language: "冰岛语", family: "Indo-European", speakers: "36万", fact: "冰岛语保留了很多古诺尔斯语的特点。", neighbors: [] },
  "LU": { name: "卢森堡", flag: "🇱🇺", language: "法语/德语/卢森堡语", family: "Indo-European", speakers: "64万", fact: "卢森堡有三种官方语言。", neighbors: ["BE", "DE", "FR"] },
  "MT": { name: "马耳他", flag: "🇲🇹", language: "马耳他语/英语", family: "Afro-Asiatic", speakers: "52万", fact: "马耳他语是唯一有闪米特语源的欧盟语言。", neighbors: [] },
  "CY": { name: "塞浦路斯", flag: "🇨🇾", language: "希腊语/土耳其语", family: "Indo-European", speakers: "120万", fact: "塞浦路斯有希腊语和土耳其语两种官方语言。", neighbors: [] },
  "PY": { name: "巴拉圭", flag: "🇵🇾", language: "西班牙语/瓜拉尼语", family: "Indo-European", speakers: "730万", fact: "巴拉圭是南美洲唯一以西班牙语和土著语言为官方语言的国家。", neighbors: ["AR", "BO", "BR"] },
  "VE": { name: "委内瑞拉", flag: "🇻🇪", language: "西班牙语", family: "Indo-European", speakers: "2900万", fact: "委内瑞拉的西班牙语有独特的口音。", neighbors: ["CO", "BR"] },
  "EC": { name: "厄瓜多尔", flag: "🇪🇨", language: "西班牙语", family: "Indo-European", speakers: "1800万", fact: "厄瓜多尔以达尔文的进化论闻名。", neighbors: ["CO", "PE"] },
  "BO": { name: "玻利维亚", flag: "🇧🇴", language: "西班牙语/克丘亚语/艾马拉语", family: "Indo-European", speakers: "1200万", fact: "玻利维亚有三种官方语言。", neighbors: ["BR", "PY", "AR", "CL", "PE"] },
  "UY": { name: "乌拉圭", flag: "🇺🇾", language: "西班牙语", family: "Indo-European", speakers: "350万", fact: "乌拉圭是南美洲最稳定的国家之一。", neighbors: ["BR", "AR"] },
  "GT": { name: "危地马拉", flag: "🇬🇹", language: "西班牙语", family: "Indo-European", speakers: "1800万", fact: "危地马拉有22种土著语言。", neighbors: ["MX", "HN", "SV"] },
  "HN": { name: "洪都拉斯", flag: "🇭🇳", language: "西班牙语", family: "Indo-European", speakers: "1020万", fact: "洪都拉斯的西班牙语有独特的口音。", neighbors: ["GT", "SV", "NI"] },
  "SV": { name: "萨尔瓦多", flag: "🇸🇻", language: "西班牙语", family: "Indo-European", speakers: "640万", fact: "萨尔瓦多是中美洲人口最密集的国家。", neighbors: ["GT", "HN"] },
  "NI": { name: "尼加拉瓜", flag: "🇳🇮", language: "西班牙语", family: "Indo-European", speakers: "670万", fact: "尼加拉瓜湖是中美洲最大的湖泊。", neighbors: ["HN", "CR"] },
  "CR": { name: "哥斯达黎加", flag: "🇨🇷", language: "西班牙语", family: "Indo-European", speakers: "520万", fact: "哥斯达黎加是美洲最稳定的国家之一。", neighbors: ["NI", "PA"] },
  "PA": { name: "巴拿马", flag: "🇵🇦", language: "西班牙语", family: "Indo-European", speakers: "430万", fact: "巴拿马运河是世界著名的工程奇迹。", neighbors: ["CR", "CO"] },
  "CU": { name: "古巴", flag: "🇨🇺", language: "西班牙语", family: "Indo-European", speakers: "1130万", fact: "古巴的西班牙语有独特的节奏。", neighbors: [] },
  "DO": { name: "多米尼加", flag: "🇩🇴", language: "西班牙语", family: "Indo-European", speakers: "1100万", fact: "多米尼加共和国与海地共享伊斯帕尼奥拉岛。", neighbors: ["HT"] },
  "HT": { name: "海地", flag: "🇭🇹", language: "法语/海地克里奥尔语", family: "Indo-European", speakers: "1150万", fact: "海地克里奥尔语是法语的一种克里奥尔语变体。", neighbors: ["DO"] },
  "GH": { name: "加纳", flag: "🇬🇭", language: "英语", family: "Indo-European", speakers: "3200万", fact: "加纳是西非最稳定的国家之一。", neighbors: ["TG"] },
  "TZ": { name: "坦桑尼亚", flag: "🇹🇿", language: "斯瓦希里语/英语", family: "Niger-Congo", speakers: "6300万", fact: "斯瓦希里语是坦桑尼亚的官方语言。", neighbors: ["KE", "MZ", "UG"] },
  "UG": { name: "乌干达", flag: "🇺🇬", language: "英语/斯瓦希里语", family: "Niger-Congo", speakers: "4700万", fact: "乌干达被称为非洲的明珠。", neighbors: ["KE", "TZ"] },
  "LK": { name: "斯里兰卡", flag: "🇱🇰", language: "僧伽罗语/泰米尔语", family: "Indo-European", speakers: "2200万", fact: "斯里兰卡有僧伽罗语和泰米尔语两种官方语言。", neighbors: ["IN"] }
};
